current: local
environments:
  - id: local
    name: Local Docker
    kind: local-docker
    capabilities:
      runtime:
        - docker-single
      registry: true
      ingress: true
      managedRoots:
        - stack-root
    policy:
      projects:
        - id: hivewatch-local
          profiles:
            - normal
            - test
          actions:
            - deploy
            - remove
            - update
        - id: hivewatch
          profiles:
            - normal
            - test
          actions:
            - deploy
            - remove
            - update
