current: local
environments:
  - id: local
    name: Local Docker
    kind: local-docker
    capabilities:
      runtime:
        - docker-single
      managedRoot:
        shared: false
        bindSourceRoot: /opt/hiveforge
        nodes:
          - local-docker
    policy:
      projects:
        - id: hivewatch-local
          profiles:
            - normal
            - test
          actions:
            - deploy
            - remove
            - update
        - id: hivewatch
          profiles:
            - normal
            - test
          actions:
            - deploy
            - remove
            - update
